<?php
/**
 * Created by PhpStorm.
 * User: dmitriyt
 * Date: 2019-07-12
 * Time: 18:45
 */

namespace App\Controller\Api;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Image api controller.
 *
 * @Route("/image")
 */
class ImageApiController extends AbstractApiController
{
    /**
     * @param Request $request
     *
     * @Route("/upload", methods="POST", name="image_upload_url")
     * @return Response
     */
    public function action(Request $request): Response
    {
        $file = new UploadedFile($_FILES['image']['tmp_name'], $_FILES['image']['name']);
        $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
        $file->move(
            $this->getParameter('image_directory'),
            $fileName
        );

        return $this->createResponse($this->serializer->serialize($fileName, 'json'));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}